package ballmerpeak.stargate.commands;

import ballmerpeak.stargate.Player;

/**
 * represents a command generated by one of the users
 */
public interface InputCommand {
	
    /**
     * receives the player the command should be executed on
     */
	public abstract void execute(Player player);
	
}
