package ballmerpeak.stargate.commands;

/**
 * implemented by Game
 */
public interface InputCommandHandler {
    /**
     * receives the command generated by the user interface
     */
	public void receiveInput(InputCommand command);
	
	/**
	 * @param pss
	 */
	public void setPlayerSelectionStrategy(PlayerSelectionStrategy pss);
}
